# Generated by Django 5.2.8 on 2025-12-01 00:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
